export const INTEROP_PROVIDER_ROOT_NAME = 'Overlook Interop';
export const INTEROP_PROVIDER_LIBRARY_ID = 'v1';
export const INTEROP_PROVIDER_LOGICAL_ROOT = `${INTEROP_PROVIDER_ROOT_NAME}/${INTEROP_PROVIDER_LIBRARY_ID}`;
