import type { PanelAction, PanelActionName } from '../types.js';

export type PanelActionDomain = 'parsed-fields' | 'queue-recents' | 'settings' | 'panel-session';

type RoutedPanelActionName = PanelActionName | PanelAction['name'];

export const PANEL_ACTION_DOMAINS = {
  'toggle-panel': 'panel-session',
  'close-panel': 'panel-session',
  'panel/minimize': 'panel-session',
  'panel/expand': 'panel-session',
  'panel/secondary-controls-open': 'panel-session',
  'destination/select': 'panel-session',
  'destination/open-tab': 'panel-session',
  'destination/close': 'panel-session',
  'panel/history-section-open': 'panel-session',
  'panel/bookmarks-section-open': 'panel-session',
  'section/detach': 'panel-session',
  'section/restore': 'panel-session',
  'workspace/move': 'panel-session',
  'workspace/snap': 'panel-session',
  'workspace/unsnap': 'panel-session',
  'workspace/shade': 'panel-session',
  'workspace/reorder': 'panel-session',
  'start-target-picker': 'panel-session',
  'stop-target-picker': 'panel-session',
  'grab-mode/start': 'panel-session',
  'grab-mode/stop': 'panel-session',
  'target/fill-screen': 'panel-session',
  'target/set-object-fit': 'panel-session',
  'target/release': 'panel-session',
  'page-context/set': 'panel-session',
  'history/add-loaded': 'queue-recents',
  'history/remove': 'queue-recents',
  'history/pin': 'queue-recents',
  'history/mark-pinned': 'queue-recents',
  'history/delete-all': 'queue-recents',
  'history/load': 'queue-recents',
  'history/download': 'queue-recents',
  'history/select': 'queue-recents',
  'history/update-display-order': 'queue-recents',
  'selection/select-visible': 'queue-recents',
  'history-selection/toggle': 'queue-recents',
  'history-selection/select': 'queue-recents',
  'history-selection/clear': 'queue-recents',
  'active-field/set': 'parsed-fields',
  'field-unlock/toggle': 'parsed-fields',
  'field/transform': 'parsed-fields',
  'field/commit-rejected': 'parsed-fields',
  'selected-url/apply': 'parsed-fields',
  'selected-url/reject-unsupported-input': 'parsed-fields',
  'pin/current': 'queue-recents',
  'bookmark/current': 'queue-recents',
  'bookmark/load': 'queue-recents',
  'bookmark/remove': 'queue-recents',
  'bookmark/clear': 'queue-recents',
  'bookmark-selection/toggle': 'queue-recents',
  'bookmark-selection/single': 'queue-recents',
  'bookmark-selection/select': 'queue-recents',
  'bookmark-selection/clear': 'queue-recents',
  'bookmarks/page-loaded': 'queue-recents',
  'bookmarks/clear-visible': 'queue-recents',
  'bookmarks/delete-visible': 'queue-recents',
  'bookmarks/update-display-order': 'queue-recents',
  'gallery/open': 'queue-recents',
  'bookmarks/page-front': 'queue-recents',
  'bookmarks/page-back': 'queue-recents',
  'bookmarks/toggle-scope': 'queue-recents',
  'bookmarks/reload': 'queue-recents',
  'bookmarks/refresh-thumbnails': 'queue-recents',
  'settings/toggle': 'settings',
  'help/toggle': 'panel-session',
  'settings/update-visible-bookmark-soft-max': 'settings',
  'settings/update-recent-history-retention': 'settings',
  'settings/update-recent-sparse-row-display-mode': 'settings',
  'settings/update-pin-save-storage-preference': 'settings',
  'settings/update-privacy-mode': 'settings',
  'settings/update-metadata-policy': 'settings',
  'settings/update-build-info-overlay-visibility': 'settings',
  'settings/update-url-review-status-retention': 'settings',
  'settings/update-request-throttle': 'settings',
  'settings/update-neighbor-preload': 'settings',
  'settings/update-down-arrow-action': 'settings',
  'neighbor-preload/manual': 'settings',
  'settings/reset-panel-position': 'settings',
  'settings/update-workspace-layout-restore': 'settings',
  'settings/reset-workspace-layout': 'settings',
  'url-templates/load': 'parsed-fields',
  'url-template/save-step-preset': 'parsed-fields',
  'url-template/remove': 'parsed-fields',
  'url-template/update-settings': 'parsed-fields',
  'url-template/update-fields': 'parsed-fields',
  'grab-source-patterns/load': 'parsed-fields',
  'grab-source-pattern/remove': 'parsed-fields',
  'grab-source-pattern/update-settings': 'parsed-fields',
  'parsed-field-state/restore': 'parsed-fields',
  'capture/request': 'queue-recents',
  'capture/repair-selected': 'queue-recents',
  'capture/permission-retry': 'queue-recents',
  'capture/start': 'queue-recents',
  'capture/complete': 'queue-recents',
  'capture/clear': 'queue-recents',
  'capture/delete': 'queue-recents',
  'capture/cleanup-orphans': 'queue-recents',
  'capture/preview': 'queue-recents',
  'blob-key/setup': 'settings',
  'blob-key/unlock': 'settings',
  'blob-key/clear': 'settings',
  'blob-key/export': 'settings',
  'blob-key/import': 'settings',
  'blob-key/status': 'settings',
  'import-export/start': 'settings',
  'import-export/complete': 'settings',
  'import-export/error': 'settings',
  'import/restore-preview-ready': 'settings',
  'pcloud-backup/status': 'settings',
  'pcloud-backup/busy': 'settings',
  'pcloud-backup/message': 'settings',
  'pcloud-backup/upload-complete': 'settings',
  'pcloud-backup/upload-error': 'settings',
  'pcloud-backup/error': 'settings',
  'cloud-backup/connect': 'settings',
  'cloud-backup/backup-now': 'settings',
  'cloud-backup/choose-restore': 'settings',
  'cloud-backup/retry': 'settings',
  'cloud-backup/disconnect': 'settings',
  'cloud-backup/preview-restore': 'settings',
  'export/history': 'settings',
  'export/bookmarks': 'settings',
  'export/image': 'settings',
  'export/encrypted-image': 'settings',
  'export/url-review-status': 'settings',
  'clear/url-review-status': 'settings',
  'import/history': 'settings',
  'import/bookmarks': 'settings',
  'import/image': 'settings',
  'import/encrypted-image': 'settings',
  'import/url-review-status': 'settings',
  'import/confirm-restore-preview': 'settings',
  'import/cancel-restore-preview': 'settings',
  'recall/open': 'queue-recents',
  'recall/close': 'queue-recents',
  'recall/load-start': 'queue-recents',
  'recall/reload': 'queue-recents',
  'recall/load-more': 'queue-recents',
  'recall/load-complete': 'queue-recents',
  'recall/error': 'queue-recents',
  'recall/message-clear': 'queue-recents',
  'recall-selection/toggle': 'queue-recents',
  'recall-selection/select': 'queue-recents',
  'recall-selection/clear': 'queue-recents',
  'recall/selected': 'queue-recents',
  'recall/clear-results': 'queue-recents',
  'recall/delete-all': 'queue-recents',
  'recall/complete': 'queue-recents',
  'pcloud-backup/restore-candidates-loaded': 'settings',
  'pcloud-backup/restore-downloaded': 'settings',
  'pcloud-backup/restore-error': 'settings',
  'storage/update': 'settings',
  'undo-last': 'panel-session',
  'slideshow-start': 'panel-session',
  'slideshow-stop': 'panel-session',
  'slideshow-pause': 'panel-session',
  'slideshow-resume': 'panel-session',
  'retry-start': 'panel-session',
  'retry-stop': 'panel-session',
  'navigate-next': 'panel-session',
  'navigate-previous': 'panel-session',
  'stop-all': 'panel-session',
} as const satisfies Record<RoutedPanelActionName, PanelActionDomain>;

type ActionNameForDomain<Domain extends PanelActionDomain> = {
  [Name in RoutedPanelActionName]: (typeof PANEL_ACTION_DOMAINS)[Name] extends Domain ? Name : never;
}[RoutedPanelActionName];

type PanelActionForName<Name extends RoutedPanelActionName> = PanelAction extends infer Action
  ? Action extends { readonly name: infer Names }
    ? Name extends Names
      ? Omit<Action, 'name'> & { readonly name: Name }
      : never
    : never
  : never;

export type PanelActionForDomain<Domain extends PanelActionDomain> = {
  [Name in ActionNameForDomain<Domain>]: PanelActionForName<Name>;
}[ActionNameForDomain<Domain>];

export function isPanelActionForDomain<Domain extends PanelActionDomain>(
  action: PanelAction,
  domain: Domain,
): action is PanelActionForDomain<Domain> {
  return PANEL_ACTION_DOMAINS[action.name] === domain;
}

export function assertNeverAction(action: never): never {
  throw new Error(`Unhandled panel action: ${JSON.stringify(action)}`);
}
